### ISSUE TITLE
Correct export in TS definition

### ISSUE THREAD

**Issue by websitevirtuoso** [jquense/expr#18]
I started to use bun by many reasons. and first notices that it throw error
```
viktord@blade:~/Projects/renthome/dashboard$ bun run build
$ vite build
vite v4.4.11 building for production...
✓ 1858 modules transformed.
✓ built in 8.21s
"getter" is not exported by "node_modules/property-expr/index.js", imported by "node_modules/yup/index.esm.js".
file: /home/viktord/Projects/renthome/dashboard/node_modules/yup/index.esm.js:1:9
1: import { getter, forEach, split, normalizePath, join } from 'property-expr';
            ^
2: import { camelCase, snakeCase } from 'tiny-case';
3: import toposort from 'toposort';
error during build:
RollupError: "getter" is not exported by "node_modules/property-expr/index.js", imported by "node_modules/yup/index.esm.js".
    at error (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ChildScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ClassBodyScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at FunctionScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///home/viktord/Projects/renthome/dashboard/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
error: script "build" exited with code 1 (SIGHUP)
```

![image](https://github.com/jquense/expr/assets/5112918/85a5c619-e281-43f8-919f-ced88891c4da)

I am also using nodejs v20
I think we already have PR to fix it
https://github.com/jquense/expr/pull/16/files
How can I assist to merge this PR?

**Comment by seamuslowry** [comment]
Did you ever find a fix for this? The merged PR is in, but this error seems to come from the `index.js` not a TS definition.
